server:
  port: 8081
  servlet:
    context-path: /mypomaner
spring:
  datasource:
    #Asia/Shanghai
    url: jdbc:mysql://localhost:3306/mypomaner?useUnicode=true&characterEncodidng=utf-8&allowMultiQueries=true&useSLL=false&serverTimezone=GMT%2B8
    username: root
    password: root123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      #????????????????????????
      connection-timeout: 60000
      #??????????????????? ??0???????????????????????10000???10??? ????600000?10???
      idle-timeout: 600000
      #???????????????????????????????????????????????????????????????????????? ?????????????????????????????????????? ?0????????????????????idleTimeout??? ????1800000?30???
      max-lifetime: 1800000
      #???????????????????????connectionTimeout????????????250??? ????5000
      validationTimeout: 250
      connection-test-query: SELECT 1
      #mybatis-plus:
      #  configuration:
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:lockback.xml
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: '*'
        #include: '*'
      #include: shutdown

codeTemplateFilePath: /mypomaner/src/main/resources/codetemplate
codeOutPutFilePath: /temp

