ALTER TABLE TBL_PROJECT_CONFIG ADD COLUMN FILE_NAME_CONVERT int;

update TBL_PROJECT_CONFIG set FILE_NAME_CONVERT = 1;

ALTER TABLE TBL_PROJECT_TABLE ADD COLUMN FILE_NAME_CONVERT int;

update TBL_PROJECT_TABLE set FILE_NAME_CONVERT = 1;

ALTER TABLE TBL_PROJECT_TABLE ADD COLUMN INDEX_NAME varchar(20);

ALTER TABLE TBL_PROJECT_TABLE ADD COLUMN CREATE_NAME varchar(20);

ALTER TABLE TBL_PROJECT_FIELD  ADD COLUMN INDEX_STATUS int ;


